# Generated by Django 3.2 on 2021-05-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_auto_20210505_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
