# Generated by Django 3.2 on 2021-05-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_alter_property_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
