# Generated by Django 3.2 on 2021-05-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0005_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale')], default='Sale', max_length=10),
        ),
    ]
